### ISSUE TITLE
Please decompile the prototypes as well!

### ISSUE THREAD

**Issue by PhilHubNew2022** [brunovalads/the-flintstones-snes#1]
Hi there! I am very glad to see someone is finally taking the game apart to see what unused things might be hidden inside! Cutting Room Floor did a very lazy job not looking in deep enough. Its only up to you to do it! I am very interested to find unused content in this game because I need unused assets for my future project! 

Unused assets I need are sprites, fonts, music, and sound effects! 

In order to accomplish this, you must decompile the Sega Genesis version first and you can decompile the Super Nes prototypes later on. 

I want the Genesis prototype to be a higher demand because I always wanted to see more of the Genesis version which was never released!

Hope you can do it. I am hoping you can find sprites from the missing snow level and the 2nd level of Bedrock stage. Let me know if you find unused sprites and sound effects from the prototypes.

**Comment by brunovalads** [comment]
Hi! I'm glad more people are interested on this project.
The sad part is that I have close to no free time to work as I'd like to on this project.
Currently I'm disassembling Porky Pig's Haunted Holiday, which itself takes a lot of effort in this little time I have.
Also, my intention is to work first on the Snes version, as much as I can, before tackling the prototypes.
Feel free to research any of them and ask some specific stuff, I still can sporadically help!

**Comment by PhilHubNew2022** [comment]
> Hi! I'm glad more people are interested on this project. The sad part is that I have close to no free time to work as I'd like to on this project. Currently I'm disassembling Porky Pig's Haunted Holiday, which itself takes a lot of effort in this little time I have. Also, my intention is to work first on the Snes version, as much as I can, before tackling the prototypes. Feel free to research any of them and ask some specific stuff, I still can sporadically help!

I don't care about Porky Pig Haunted Holiday. You are only wasting time on it. Well, maybe you have time to decompile on Sunday and weekends if you have day off? unless you are working full time (what a sad world we live in lmao). Excuses or not, its only 1 prototype of the Flintstones and with fewer content compared to a completed and already released game I think you are just not into data mining prototypes for some reason. As useless you might sound or you just too busy to bring filthy income on the table instead of considering about saving me some time and trouble from doing it myself. In fact the game is just too underrated for being poorly based on a short lived and not so popular anymore film, more people like you would not care about touching it or its lost content from beta versions. I am going to forget that I ask you for this. Do not message me again. bye.

**Comment by brunovalads** [comment]
I was polite, you weren't. I'm not your employee, don't expect people do what you "command". Bye.
